# Generated by Django 4.0.4 on 2022-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default='comment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fname',
            field=models.CharField(max_length=122),
        ),
    ]
